name: mlops-example-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://tensorflow/tensorflow:latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl

      - name: Install Node.js using nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 20.18.0
          nvm use 20.18.0
          node -v

      - name: Install CML
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          npm install -g @dvcorg/cml

      # ✅ Add Node.js and npm to PATH to fix cml-publish issue
      - name: Add Node.js and npm to PATH
        run: |
          export PATH="$HOME/.nvm/versions/node/v20.18.0/bin:$PATH"
          export PATH="$(npm get prefix)/bin:$PATH"
          cml -h

      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python model.py
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish model_results.png --md >> report.md
          
          cml-send-comment report.md
