name: mlops-example-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Train my model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python model.py
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish model_results.png --md >> report.md || echo "cml-publish failed"
          cml-send-comment report.md || echo "cml-send-comment failed"
